updated AppImage build config for Linux, embedded tests work now

diff --git a/src/AppImageBuilder.yml b/src/AppImageBuilder.yml
--- a/src/AppImageBuilder.yml
+++ b/src/AppImageBuilder.yml
@@ -1,12 +1,13 @@
 # appimage-builder recipe see https://appimage-builder.readthedocs.io for details
+# To be called like this from SASfit root source dir:
+#   appimage-builder --recipe src/AppImageBuilder.yml
+# For cleanup during consecutive runs:
+#   rm -Rf ../sasfit_*_linux64* && (cd saskit && rm -Rf build/*/dqkit saskit_* bin) && sh src/appveyor/4_build.sh
 version: 1
-script:
-  - echo "Removing any existing appdir '$APPDIR'"
-  - rm -Rf "$APPDIR" | true
 AppDir:
   # assuming this file resides in sasfit/src/,
   # addresses the package dir created by CMake previously
-  path: ../../sasfit_210715150658_linux64_debug
+  path: ../sasfit_210715150658_linux64_debug
   app_info:
     id: SASfit
     name: SASfit
@@ -14,26 +15,23 @@ AppDir:
     version: latest
     exec: saskit
     exec_args: $APPDIR/sasfit.vfs/main.tcl $@
-  before_bundle: |
-    echo "before_bundle"
+  before_bundle:
+    - echo "Running appimage-build in '$(pwd)'"
   after_bundle:
     - echo "after_bundle"
+    #
     # adjustments to the current layout CMake prepares
     - (cd "$APPDIR" && rm -Rf sasfit sasfit.sh lib) # files not needed anymore, FIXME
-    - cd .. # changing to SASfit root dir
-    - cp -R sasfit.vfs "$APPDIR"/
+    #
     # FIXME: generate proper icons from the svg
     - mkdir -p "$APPDIR"/usr/share/icons && cp doc/images/sasfit_icon.svg "$APPDIR"/usr/share/icons/
+    #
     # Copy the saskit dqkit to let it get the proper libc interpreter update
     - cp saskit/build/*/dqkit/dqkit.bin "$APPDIR"/saskit
-    #- killall appimage-builder; exit
-    #- export TCLSH="$APPDIR/sasfit-src/src/tcl/linux64/bin/tclsh8.4"
-    #- cd "$APPDIR/sasfit-src/saskit" && sh gen/common.sh
   before_runtime:
     - echo "before_runtime"
   after_runtime: |
     echo "after_runtime"
-    cd .. # changing to SASfit root dir
     #
     # copy modified dqkit back to the saskit source for reassembling
     SASKIT_BUILD_PATH="$(find saskit/build/ -mindepth 1 -maxdepth 1 -type d)"
@@ -72,21 +70,7 @@ AppDir:
     - libstdc++6
   files:
     include:
-    - sasfit-src/doc/images/sasfit_icon*
-    - sasfit-src/doc/manual/sasfit.pdf
-    - sasfit-src/data/test.dat
-    - sasfit-src/plugins/*
-    - sasfit-src/sasfit.vfs/**
-    - sasfit-src/saskit/**
-    - sasfit-src/src/**
-    - sasfit-src/Readme.md
-    - sasfit-src/sasfit.sh
-    - sasfit-src/config.ini
-    - sasfit-src/Copyright_notice.txt
-    - sasfit-src/KNOWN_BUGS.txt
-    - sasfit-src/CHANGES.txt
-    - sasfit-src/examples.zip
-    - sasfit-src/COPYING.txt
+    - sasfit.vfs/**
     exclude:
     - opt/libc/usr/share/doc
     - usr/lib/x86_64-linux-gnu/gconv
@@ -97,10 +81,29 @@ AppDir:
     - usr/share/doc/*/TODO.*
     - usr/include
   test:
-    ubuntu-xenial:
+    # Tests require docker to be installed and its socket (e.g. /run/docker.sock)
+    # being accessible for the current user (being in the 'docker' group)
+    # for Ubuntu: 'apt install docker.io && adduser $(whoami) docker'
+    ubuntu:
       image: appimagecrafters/tests-env:ubuntu-xenial
-      command: ./AppRun
+      command: sh -c 'timeout 10 ./AppRun; [ "$?" -eq 124 ]'
       use_host_x: true
+    debian:
+      image: appimagecrafters/tests-env:debian-stable
+      command: sh -c 'timeout 10 ./AppRun; [ "$?" -eq 124 ]'
+      use_host_x: True
+    centos:
+      image: appimagecrafters/tests-env:centos-7
+      command: sh -c 'timeout 10 ./AppRun; [ "$?" -eq 124 ]'
+      use_host_x: True
+    fedora:
+      image: appimagecrafters/tests-env:fedora-30
+      command: sh -c 'timeout 10 ./AppRun; [ "$?" -eq 124 ]'
+      use_host_x: True
+    arch:
+      image: appimagecrafters/tests-env:archlinux-latest
+      command: sh -c 'timeout 10 ./AppRun; [ "$?" -eq 124 ]'
+      use_host_x: True
 AppImage:
   arch: x86_64
   update-information: guess
